name: "document_scanner"
description: "Document Scanner"
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  animated_snack_bar: ^0.4.0
  bloc: ^8.1.4
  camera: ^0.10.5+9
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.16.0
  cunning_document_scanner: ^1.2.2
  equatable: ^2.0.5
  file_picker: ^8.0.0+1
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  firebase_storage: ^11.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  image_gallery_saver: ^2.0.3
  image_preview: ^1.0.7
  open_file: ^3.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  syncfusion_flutter_pdf: ^25.1.42
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#000000"
  image: "assets/images/splash.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"